### ISSUE TITLE
Some feature requests for the website

### ISSUE THREAD

**Issue by stevemao** [jshint/jshint.github.io#13]
Moved from https://github.com/jshint/jshint/issues/2244#issuecomment-77864727

Can we add autocomplete for "Jump to docs"?
Can we add "go back to top" button after each option in the table?
Can we add a changelog page or migration guide? I can't find any deprecated option list on the page. It would be great for reference.

Thanks a lot!

**Comment by jugglinmike** [comment]
Each of the features you are requesting here are unrelated to each other. That's why [I requested](https://github.com/jshint/jshint/issues/2244#issuecomment-77921702) that they be made with separate issues--it will make discussing them and tracking their resolution easier.

**Comment by stevemao** [comment]
oops
