### ISSUE TITLE
No description of "extends" and "overrides" options

### ISSUE THREAD

**Issue by narqo** [jshint/jshint.github.io#17]
I couldn't find any mentions about (not so) new `extends` and `overrides` on the jshint.com website currently. It would be great to have some.

**Comment by c32hedge** [comment]
Looks like they are here now: http://jshint.com/docs/cli/ as a result of gh-24 (and my jshint/jshint#1902 for `extends` was marked resolved) -- is this resolved now?

**Comment by jugglinmike** [comment]
It is! Thanks for the heads-up

**Comment by narqo** [comment]
Nice to hear that. Thanks! 👍🏻
