### ISSUE TITLE
docs/options/ points to JSCS which itself is deprecated

### ISSUE THREAD

**Issue by xmjl** [jshint/jshint.github.io#57]
For some JSHint-deprecated options for style checking, the "JSHint Options" page points to JSCS at https://github.com/jscs-dev/node-jscs. That repository says it is archived, read-only, unmaintained, and mentions it is merged with ESLint.
Probably makes sense to update the link.

**Comment by jugglinmike** [comment]
I'm not aware of an alternative style checker, but if anyone has a suggestion, we'll certainly consider a patch!
