### ISSUE TITLE
Typo on About page

### ISSUE THREAD

**Issue by joeyc773** [jshint/jshint.github.io#59]
https://jshint.com/about/

"Only 15% of all programs **linted** on jshint.com pass the JSHint checks."

I _assume_ this is supposed to say **listed** or **linked** but not sure which.

**Comment by jugglinmike** [comment]
Thanks for taking the time to write a report! I think the current text is correct in this case; although it predates my involvement, I believe it was meant to describe that code that is input on jshint.com. In other words, the phrase "programs linted on jshint.com" means "programs supplied to the demo on the JSHint website."
